#compdef brave-search
# brave-search completion for zsh, bridged from the picocli-generated script through
# bashcompinit; source this file from your zsh profile.
#
# brave-search Bash Completion
# =======================
#
# Bash completion support for the `brave-search` command,
# generated by [picocli](https://picocli.info/) version 4.7.7.
#
# Installation
# ------------
#
# 1. Source all completion scripts in your .bash_profile
#
#   cd $YOUR_APP_HOME/bin
#   for f in $(find . -name "*_completion"); do line=". $(pwd)/$f"; grep "$line" ~/.bash_profile || echo "$line" >> ~/.bash_profile; done
#
# 2. Open a new bash console, and type `brave-search [TAB][TAB]`
#
# 1a. Alternatively, if you have [bash-completion](https://github.com/scop/bash-completion) installed:
#     Place this file in a `bash-completion.d` folder:
#
#   * /etc/bash-completion.d
#   * /usr/local/etc/bash-completion.d
#   * ~/bash-completion.d
#
# Documentation
# -------------
# The script is called by bash whenever [TAB] or [TAB][TAB] is pressed after
# 'brave-search (..)'. By reading entered command line parameters,
# it determines possible bash completions and writes them to the COMPREPLY variable.
# Bash then completes the user input if only one entry is listed in the variable or
# shows the options if more than one is listed in COMPREPLY.
#
# References
# ----------
# [1] http://stackoverflow.com/a/12495480/1440785
# [2] http://tiswww.case.edu/php/chet/bash/FAQ
# [3] https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
# [4] http://zsh.sourceforge.net/Doc/Release/Options.html#index-COMPLETE_005fALIASES
# [5] https://stackoverflow.com/questions/17042057/bash-check-element-in-array-for-elements-in-another-array/17042655#17042655
# [6] https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html#Programmable-Completion
# [7] https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh/27853970#27853970
#

if [ -n "$BASH_VERSION" ]; then
  # Enable programmable completion facilities when using bash (see [3])
  shopt -s progcomp
elif [ -n "$ZSH_VERSION" ]; then
  # Make alias a distinct command for completion purposes when using zsh (see [4])
  setopt COMPLETE_ALIASES
  alias compopt=complete

  # Enable bash completion in zsh (see [7])
  # Only initialize completions module once to avoid unregistering existing completions.
  if ! type compdef > /dev/null; then
    autoload -U +X compinit && compinit
  fi
  autoload -U +X bashcompinit && bashcompinit
fi

# CompWordsContainsArray takes an array and then checks
# if all elements of this array are in the global COMP_WORDS array.
#
# Returns zero (no error) if all elements of the array are in the COMP_WORDS array,
# otherwise returns 1 (error).
function CompWordsContainsArray() {
  declare -a localArray
  localArray=("$@")
  local findme
  for findme in "${localArray[@]}"; do
    if ElementNotInCompWords "$findme"; then return 1; fi
  done
  return 0
}
function ElementNotInCompWords() {
  local findme="$1"
  local element
  for element in "${COMP_WORDS[@]}"; do
    if [[ "$findme" = "$element" ]]; then return 1; fi
  done
  return 0
}

# The `currentPositionalIndex` function calculates the index of the current positional parameter.
#
# currentPositionalIndex takes three parameters:
# the command name,
# a space-separated string with the names of options that take a parameter, and
# a space-separated string with the names of boolean options (that don't take any params).
# When done, this function echos the current positional index to std_out.
#
# Example usage:
# local currIndex=$(currentPositionalIndex "mysubcommand" "$ARG_OPTS" "$FLAG_OPTS")
function currentPositionalIndex() {
  local commandName="$1"
  local optionsWithArgs="$2"
  local booleanOptions="$3"
  local previousWord
  local result=0

  for i in $(seq $((COMP_CWORD - 1)) -1 0); do
    previousWord=${COMP_WORDS[i]}
    if [ "${previousWord}" = "$commandName" ]; then
      break
    fi
    if [[ "${optionsWithArgs}" =~ ${previousWord} ]]; then
      ((result-=2)) # Arg option and its value not counted as positional param
    elif [[ "${booleanOptions}" =~ ${previousWord} ]]; then
      ((result-=1)) # Flag option itself not counted as positional param
    fi
    ((result++))
  done
  echo "$result"
}

# compReplyArray generates a list of completion suggestions based on an array, ensuring all values are properly escaped.
#
# compReplyArray takes a single parameter: the array of options to be displayed
#
# The output is echoed to std_out, one option per line.
#
# Example usage:
# local options=("foo", "bar", "baz")
# local IFS=$'\n'
# COMPREPLY=($(compReplyArray "${options[@]}"))
function compReplyArray() {
  declare -a options
  options=("$@")
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local i
  local quoted
  local optionList=()

  for (( i=0; i<${#options[@]}; i++ )); do
    # Double escape, since we want escaped values, but compgen -W expands the argument
    printf -v quoted %q "${options[i]}"
    quoted=\'${quoted//\'/\'\\\'\'}\'

    optionList[i]=$quoted
  done

  # We also have to add another round of escaping to $curr_word.
  curr_word=${curr_word//\\/\\\\}
  curr_word=${curr_word//\'/\\\'}

  # Actually generate completions.
  local IFS=$'\n'
  echo -e "$(compgen -W "${optionList[*]}" -- "$curr_word")"
}

# Bash completion entry point function.
# _complete_brave-search finds which commands and subcommands have been specified
# on the command line and delegates to the appropriate function
# to generate possible options and subcommands for the last specified subcommand.
function _complete_brave-search() {
  # Edge case: if command line has no space after subcommand, then don't assume this subcommand is selected (remkop/picocli#1468).
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} version" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} config" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} web" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} context" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} news" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} videos" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} images" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} suggest" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} spellcheck" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} places" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} rich" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} answers" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} completion" ];    then _picocli_brave-search; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} config set-key" ];    then _picocli_brave-search_config; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} config unset-key" ];    then _picocli_brave-search_config; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} config show" ];    then _picocli_brave-search_config; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} config repair-permissions" ];    then _picocli_brave-search_config; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} places search" ];    then _picocli_brave-search_places; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} places details" ];    then _picocli_brave-search_places; return $?; fi
  if [ "${COMP_LINE}" = "${COMP_WORDS[0]} places describe" ];    then _picocli_brave-search_places; return $?; fi

  # Find the longest sequence of subcommands and call the bash function for that subcommand.
  local cmds0=(version)
  local cmds1=(config)
  local cmds2=(web)
  local cmds3=(context)
  local cmds4=(news)
  local cmds5=(videos)
  local cmds6=(images)
  local cmds7=(suggest)
  local cmds8=(spellcheck)
  local cmds9=(places)
  local cmds10=(rich)
  local cmds11=(answers)
  local cmds12=(completion)
  local cmds13=(config set-key)
  local cmds14=(config unset-key)
  local cmds15=(config show)
  local cmds16=(config repair-permissions)
  local cmds17=(places search)
  local cmds18=(places details)
  local cmds19=(places describe)

  if CompWordsContainsArray "${cmds19[@]}"; then _picocli_brave-search_places_describe; return $?; fi
  if CompWordsContainsArray "${cmds18[@]}"; then _picocli_brave-search_places_details; return $?; fi
  if CompWordsContainsArray "${cmds17[@]}"; then _picocli_brave-search_places_search; return $?; fi
  if CompWordsContainsArray "${cmds16[@]}"; then _picocli_brave-search_config_repairpermissions; return $?; fi
  if CompWordsContainsArray "${cmds15[@]}"; then _picocli_brave-search_config_show; return $?; fi
  if CompWordsContainsArray "${cmds14[@]}"; then _picocli_brave-search_config_unsetkey; return $?; fi
  if CompWordsContainsArray "${cmds13[@]}"; then _picocli_brave-search_config_setkey; return $?; fi
  if CompWordsContainsArray "${cmds12[@]}"; then _picocli_brave-search_completion; return $?; fi
  if CompWordsContainsArray "${cmds11[@]}"; then _picocli_brave-search_answers; return $?; fi
  if CompWordsContainsArray "${cmds10[@]}"; then _picocli_brave-search_rich; return $?; fi
  if CompWordsContainsArray "${cmds9[@]}"; then _picocli_brave-search_places; return $?; fi
  if CompWordsContainsArray "${cmds8[@]}"; then _picocli_brave-search_spellcheck; return $?; fi
  if CompWordsContainsArray "${cmds7[@]}"; then _picocli_brave-search_suggest; return $?; fi
  if CompWordsContainsArray "${cmds6[@]}"; then _picocli_brave-search_images; return $?; fi
  if CompWordsContainsArray "${cmds5[@]}"; then _picocli_brave-search_videos; return $?; fi
  if CompWordsContainsArray "${cmds4[@]}"; then _picocli_brave-search_news; return $?; fi
  if CompWordsContainsArray "${cmds3[@]}"; then _picocli_brave-search_context; return $?; fi
  if CompWordsContainsArray "${cmds2[@]}"; then _picocli_brave-search_web; return $?; fi
  if CompWordsContainsArray "${cmds1[@]}"; then _picocli_brave-search_config; return $?; fi
  if CompWordsContainsArray "${cmds0[@]}"; then _picocli_brave-search_version; return $?; fi

  # No subcommands were specified; generate completions for the top-level command.
  _picocli_brave-search; return $?;
}

# Generates completions for the options and subcommands of the `brave-search` command.
function _picocli_brave-search() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}

  local commands="version config web context news videos images suggest spellcheck places rich answers completion"
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `version` subcommand.
function _picocli_brave-search_version() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `config` subcommand.
function _picocli_brave-search_config() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}

  local commands="set-key unset-key show repair-permissions"
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `web` subcommand.
function _picocli_brave-search_web() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--all-pages' '--enable-rich-callback' '--extra-snippets' '--help' '--include-fetch-metadata' '--no-color' '--operators' '--pretty' '--quiet' '--spellcheck' '--text-decorations' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--exclude-site' '--freshness' '--goggle' '--goggle-file' '--include-site' '--loc-city' '--loc-country' '--loc-lat' '--loc-long' '--loc-postal-code' '--loc-state' '--loc-state-name' '--loc-timezone' '--max-pages' '--output' '--page' '--result-filter' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '--units' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values
  local units_option_args=("metric" "imperial") # --units values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--exclude-site')
      return
      ;;
    '--freshness')
      return
      ;;
    '--goggle')
      return
      ;;
    '--goggle-file')
      local IFS=$'\n'
      type compopt &>/dev/null && compopt -o filenames
      COMPREPLY=( $( compgen -f -- "${curr_word}" ) ) # files
      return $?
      ;;
    '--include-site')
      return
      ;;
    '--loc-city')
      return
      ;;
    '--loc-country')
      return
      ;;
    '--loc-lat')
      return
      ;;
    '--loc-long')
      return
      ;;
    '--loc-postal-code')
      return
      ;;
    '--loc-state')
      return
      ;;
    '--loc-state-name')
      return
      ;;
    '--loc-timezone')
      return
      ;;
    '--max-pages')
      return
      ;;
    '--page')
      return
      ;;
    '--result-filter')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '--units')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${units_option_args[@]}" ) )
      return $?
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `context` subcommand.
function _picocli_brave-search_context() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--source-metadata' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--loc-city' '--loc-country' '--loc-lat' '--loc-long' '--loc-postal-code' '--loc-state' '--loc-state-name' '--local' '--max-snippets' '--max-snippets-per-url' '--max-tokens' '--max-tokens-per-url' '--max-urls' '--output' '--page' '--safe-search' '--search-lang' '--threshold' '--timeout' '--ui-lang' '-o'"
  local autoonoff_option_args=("auto" "on" "off") # --local values
  local mode_option_args=("strict" "balanced" "lenient" "disabled") # --threshold values
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--loc-city')
      return
      ;;
    '--loc-country')
      return
      ;;
    '--loc-lat')
      return
      ;;
    '--loc-long')
      return
      ;;
    '--loc-postal-code')
      return
      ;;
    '--loc-state')
      return
      ;;
    '--loc-state-name')
      return
      ;;
    '--local')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${autoonoff_option_args[@]}" ) )
      return $?
      ;;
    '--max-snippets')
      return
      ;;
    '--max-snippets-per-url')
      return
      ;;
    '--max-tokens')
      return
      ;;
    '--max-tokens-per-url')
      return
      ;;
    '--max-urls')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--threshold')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${mode_option_args[@]}" ) )
      return $?
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `news` subcommand.
function _picocli_brave-search_news() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--all-pages' '--extra-snippets' '--help' '--include-fetch-metadata' '--no-color' '--operators' '--pretty' '--quiet' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--exclude-site' '--freshness' '--goggle' '--goggle-file' '--include-site' '--max-pages' '--output' '--page' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--exclude-site')
      return
      ;;
    '--freshness')
      return
      ;;
    '--goggle')
      return
      ;;
    '--goggle-file')
      local IFS=$'\n'
      type compopt &>/dev/null && compopt -o filenames
      COMPREPLY=( $( compgen -f -- "${curr_word}" ) ) # files
      return $?
      ;;
    '--include-site')
      return
      ;;
    '--max-pages')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `videos` subcommand.
function _picocli_brave-search_videos() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--all-pages' '--help' '--include-fetch-metadata' '--no-color' '--operators' '--pretty' '--quiet' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--max-pages' '--output' '--page' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--max-pages')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `images` subcommand.
function _picocli_brave-search_images() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--output' '--page' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `suggest` subcommand.
function _picocli_brave-search_suggest() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--rich' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--output' '--page' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `spellcheck` subcommand.
function _picocli_brave-search_spellcheck() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--output' '--page' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--page')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `places` subcommand.
function _picocli_brave-search_places() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}

  local commands="search details describe"
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `rich` subcommand.
function _picocli_brave-search_rich() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--output' '--timeout' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--timeout')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `answers` subcommand.
function _picocli_brave-search_answers() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--citations' '--entities' '--help' '--no-color' '--pretty' '--quiet' '--research' '--research-thinking' '--spellcheck' '--stream' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--idle-timeout' '--language' '--max-completion-tokens' '--model' '--output' '--page' '--research-iterations' '--research-queries' '--research-results-per-query' '--research-seconds' '--research-tokens-per-query' '--safe-search' '--search-lang' '--seed' '--stream-timeout' '--timeout' '--ui-lang' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--idle-timeout')
      return
      ;;
    '--language')
      return
      ;;
    '--max-completion-tokens')
      return
      ;;
    '--model')
      return
      ;;
    '--page')
      return
      ;;
    '--research-iterations')
      return
      ;;
    '--research-queries')
      return
      ;;
    '--research-results-per-query')
      return
      ;;
    '--research-seconds')
      return
      ;;
    '--research-tokens-per-query')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--seed')
      return
      ;;
    '--stream-timeout')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `completion` subcommand.
function _picocli_brave-search_completion() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `set-key` subcommand.
function _picocli_brave-search_config_setkey() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--stdin' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `unset-key` subcommand.
function _picocli_brave-search_config_unsetkey() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `show` subcommand.
function _picocli_brave-search_config_show() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--output'"
  local MODE_option_args=("human" "json" "jsonl" "raw") # --output values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${MODE_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `repair-permissions` subcommand.
function _picocli_brave-search_config_repairpermissions() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts=""

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `search` subcommand.
function _picocli_brave-search_places_search() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--spellcheck' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--count' '--country' '--freshness' '--geoloc' '--latitude' '--location' '--longitude' '--output' '--page' '--radius' '--safe-search' '--search-lang' '--timeout' '--ui-lang' '--units' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values
  local safeSearch_option_args=("off" "moderate" "strict") # --safe-search values
  local units_option_args=("metric" "imperial") # --units values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--count')
      return
      ;;
    '--country')
      return
      ;;
    '--freshness')
      return
      ;;
    '--geoloc')
      return
      ;;
    '--latitude')
      return
      ;;
    '--location')
      return
      ;;
    '--longitude')
      return
      ;;
    '--page')
      return
      ;;
    '--radius')
      return
      ;;
    '--safe-search')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${safeSearch_option_args[@]}" ) )
      return $?
      ;;
    '--search-lang')
      return
      ;;
    '--timeout')
      return
      ;;
    '--ui-lang')
      return
      ;;
    '--units')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${units_option_args[@]}" ) )
      return $?
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `details` subcommand.
function _picocli_brave-search_places_details() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--output' '--timeout' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--timeout')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Generates completions for the options and subcommands of the `describe` subcommand.
function _picocli_brave-search_places_describe() {
  # Get completion data
  local curr_word=${COMP_WORDS[COMP_CWORD]}
  local prev_word=${COMP_WORDS[COMP_CWORD-1]}

  local commands=""
  local flag_opts="'--help' '--no-color' '--pretty' '--quiet' '--verbose' '--version' '-V' '-h'"
  local arg_opts="'--api-version' '--connect-timeout' '--output' '--timeout' '-o'"
  local output_option_args=("human" "json" "jsonl" "raw") # --output values

  type compopt &>/dev/null && compopt +o default

  case ${prev_word} in
    '--api-version')
      return
      ;;
    '--connect-timeout')
      return
      ;;
    '--timeout')
      return
      ;;
    '-o'|'--output')
      local IFS=$'\n'
      COMPREPLY=( $( compReplyArray "${output_option_args[@]}" ) )
      return $?
      ;;
  esac

  if [[ "${curr_word}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flag_opts} ${arg_opts}" -- "${curr_word}") )
  else
    local positionals=""
    local IFS=$'\n'
    COMPREPLY=( $(compgen -W "${commands// /$'\n'}${IFS}${positionals}" -- "${curr_word}") )
  fi
}

# Define a completion specification (a compspec) for the
# `brave-search`, `brave-search.sh`, and `brave-search.bash` commands.
# Uses the bash `complete` builtin (see [6]) to specify that shell function
# `_complete_brave-search` is responsible for generating possible completions for the
# current word on the command line.
# The `-o default` option means that if the function generated no matches, the
# default Bash completions and the Readline default filename completions are performed.
complete -F _complete_brave-search -o default brave-search brave-search.sh brave-search.bash
